def start_profile() -> int: ...
def record_queries(request_id: int, path: str, method: str, status: int, queries: list, started_at: float) -> int | None: ...
def get_request(request_id: int) -> tuple[str, str, int, list, float] | None: ...
def list_requests() -> list[tuple[int, str, str, int, int, float, float]]: ...
def max_requests() -> int: ...
